### PR TITLE
Use same relative path for SettingsFilename as TestSuiteFilename

### PR DESCRIPTION
**Pull request by jansaris**
Fixed that the relative location towards the nbits and nbiset file are the same
<nbi testSuite="TestCases.nbits" settings="Settings.nbiset" />

### CODE REVIEW

**Comment by Seddryck** [comment]
Thx. I will check this PR tonight but already sounds correct.

**Comment by Seddryck** [comment]
Thx for your contribution. Greatly appreciated.

**Comment by Seddryck** [comment]
@jansaris: The fix wasn't correct in case we're not using an external file for the settings. I've made an adaptation to your fix and it's now available in the build https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99051

**Comment by jansaris** [comment]
Thx for fixing and writing the test. I didn't know where to start with writing the unit test for this situation.
I will test and integrate the solution next monday

**Pull request merged**
