### PR TITLE
Read environment variables from process rather than user scope

### LINKED ISSUE #717: Using process scoped environment variables to populate NBi variable
Hi @Seddryck ,

I will not be able to do any real C# code changes but at least I can contribute the full description and reasoning. 
This discussion originally started in #410 . As I assume this is just a one line code check I have created PR #718 

# background 

## environment variables

Windows systems seem to have three kind of environment variables process, system and user scope.

System and user scope are in general set with the configuration dialog from the start menu:
image

Process based environment variables are in PowerShell just set by `$Env:MYVAR="value"`.

## NBi

The usage of environment variables is explained at http://www.nbi.io/docs/variable-define/#environment-variable .

## Automation

I assume NBi is most of the time used in automatic testing and in DevOps pipelines.
Moreover, most likely NBi scripts contain references that are created as part of an Azure DevOps pipeline and thus connections strings and server names must be dynamic.

Azure DevOps and most likely any other build agent Jenkins/Bamboo/etc. have the option to pass in environment variables. In Azure DevOps this is easly done and the suggested way to pass in any secret values. ( https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables ) 

Currently my Azure DevOps pipelines do hack the nbits file to adjust several settings instead....

# solution

The relevant code is at: [EnvironmentScalarResolver.cs](https://github.com/Seddryck/NBi/blob/90e0a283fbac3b69ce37551e3788bad25a2c8042/NBi.Core/Scalar/Resolver/EnvironmentScalarResolver.cs#L21C16-L21C16)

The documentation of the API is at https://learn.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-7.0#system-environment-getenvironmentvariable(system-string) .

Which states that:
_All environment variables that are provided to it by the parent process that created it. For example, a .NET application launched from a console window inherits all of the console window's environment variables._

_If there is no parent process, per-machine and per-user environment variables are used instead. For example, a new console window has all per-machine and per-user environment variables defined at the time it was launched._

As a result I conclude, that we just have to switch from

```
            var value = Environment.GetEnvironmentVariable(args.Name, EnvironmentVariableTarget.User);
```

to

```
            var value = Environment.GetEnvironmentVariable(args.Name);
```

As a result it should be backwards compatible and in addition work for variables set at process scope...

### PR DESCRIPTION
**Pull request by fmms**
Adjust to expected behavior and easier use in build systems.

Documentation of the different scopes of environment variables is at https://learn.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-7.0#system-environment-getenvironmentvariable(system-string) .

Solves #717 

I have not tested this myself as I have no corresponding build environment, but this should solve it ...

### CODE REVIEW

**Comment by Seddryck** [comment]
Thx I'll check this tonight.

**Comment by Seddryck** [comment]
The issue is related to this part of the doc regarding environment variables

> If there is no parent process, per-machine and per-user environment variables are used instead. For example, a new console window has all per-machine and per-user environment variables defined at the time it was launched.

In the case of NUnit there is a parent process, so per-user environment variables are not pushed in the process scope.

**Comment by Seddryck** [comment]
I Can't figure out why the test is not working on AppVeyor when it works on Visual Studio. I took the time to review some details in the setup of the test environment on AppVeyor (QA related) but it's just to be sure that we are not blocked further. Will probably give another try tonight.

**Comment by fmms** [comment]
thank you so much for fixing this @Seddryck . You will be part of my presentation at SQL Konferenz. ;)
When will 1.24 be released?

**Comment by Seddryck** [comment]
> thank you so much for fixing this @Seddryck . 

Just find out the issue with tests running in parallel and adding/removing the same variables.

>You will be part of my presentation at SQL Konferenz. ;) 

I saw that ... FYI I presented NBi 6-7 years ago at SQL Konferenz :-D

>When will 1.24 be released?

I'll do some dependencies bump and then will release 1.24

**Comment by fmms** [comment]
i was in your audience at SQL Konferenz back then... ;)

**Pull request merged**
